name: Deploy Pipeline

on:
  push:
    branches: [ main ]
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event.workflow_run.conclusion == 'success'
    
    environment:
      name: staging
      url: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: deployment-package
        path: ./artifacts
    
    - name: Extract deployment package
      run: |
        cd artifacts
        tar -xzf deployment.tar.gz
    
    - name: Install production dependencies
      run: |
        cd artifacts
        npm ci --production
    
    - name: Create GitHub Pages content
      run: |
        mkdir -p public
        cat > public/index.html << 'EOF'
        <!DOCTYPE html>
        <html>
        <head>
            <title>Calculator API - CI/CD Pipeline</title>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <style>
                body { font-family: Arial, sans-serif; margin: 40px; }
                .container { max-width: 800px; margin: 0 auto; }
                .endpoint { background: #f5f5f5; padding: 15px; margin: 10px 0; border-radius: 5px; }
                .method { color: #28a745; font-weight: bold; }
                code { background: #e9ecef; padding: 2px 5px; border-radius: 3px; }
            </style>
        </head>
        <body>
            <div class="container">
                <h1>🚀 Calculator API - CI/CD Pipeline</h1>
                <p>Esta aplicación ha sido desplegada automáticamente usando GitHub Actions.</p>
                
                <h2>📡 API Endpoints</h2>
                
                <div class="endpoint">
                    <h3><span class="method">GET</span> /health</h3>
                    <p>Verifica el estado de la aplicación</p>
                </div>
                
                <div class="endpoint">
                    <h3><span class="method">POST</span> /api/calculator/add</h3>
                    <p>Suma dos números</p>
                    <code>Body: {"a": 2, "b": 3}</code>
                </div>
                
                <div class="endpoint">
                    <h3><span class="method">POST</span> /api/calculator/subtract</h3>
                    <p>Resta dos números</p>
                    <code>Body: {"a": 5, "b": 3}</code>
                </div>
                
                <div class="endpoint">
                    <h3><span class="method">POST</span> /api/calculator/multiply</h3>
                    <p>Multiplica dos números</p>
                    <code>Body: {"a": 4, "b": 5}</code>
                </div>
                
                <h2>🔄 Pipeline Status</h2>
                <p>✅ Tests ejecutados en Node.js 18, 20, 22</p>
                <p>✅ Análisis de seguridad completado</p>
                <p>✅ Build generado y almacenado</p>
                <p>✅ Deployment automático a staging</p>
                
                <h2>📊 Información del Deploy</h2>
                <p><strong>Commit:</strong> ${{ github.sha }}</p>
                <p><strong>Fecha:</strong> $(date)</p>
                <p><strong>Rama:</strong> ${{ github.ref_name }}</p>
            </div>
        </body>
        </html>
        EOF
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: deploy-staging
    if: success()
    
    environment:
      name: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Simulate production deployment
      run: |
        echo "🚀 Desplegando a producción..."
        echo "✅ Deployment a producción completado"
        echo "🔗 URL: https://mi-app-production.com"